//GAME
export const CHANGE_GAME_TITLE = 'CHANGE_GAME_TITLE'
export const CHANGE_MARKER_COORDS = 'CHANGE_MARKER_COORDS'
export const CHANGE_SET_MARKER_COORDS = 'CHANGE_SET_MARKER_COORDS'
export const CHANGE_SET_MARKER_RADIUS = 'CHANGE_SET_MARKER_RADIUS'

//PLAYER
export const CHANGE_PLAYER_NAME = 'CHANGE_PLAYER_NAME'
export const SET_HOST_TYPE = 'SET_HOST_TYPE'
export const CHANGE_ACTIVE_HANDLER = 'CHANGE_ACTIVE_HANDLER'

//UI
export const CHANGE_REQUEST_HOST_NAME = 'CHANGE_REQUEST_HOST_NAME'
export const CHANGE_NAME_HOLDER_CLASS = 'CHANGE_NAME_HOLDER_CLASS'
export const CHANGE_SETUP_CONFIG_CLASS = 'CHANGE_SETUP_CONFIG_CLASS'
export const CHANGE_SETUP_CONFIG_SETBTN_CLASS = 'CHANGE_SETUP_CONFIG_SETBTN_CLASS'
export const CHANGE_SETUP_CONFIG_STARTBTN_CLASS = 'CHANGE_SETUP_CONFIG_STARTBTN_CLASS'
