//GAME
export const CHANGE_GAME_TITLE = 'CHANGE_GAME_TITLE'
export const CHANGE_MARKER_COORDS = 'CHANGE_MARKER_COORDS'

//PLAYER
export const CHANGE_PLAYER_NAME = 'CHANGE_PLAYER_NAME'

//UI
export const CHANGE_REQUEST_HOST_NAME = 'CHANGE_REQUEST_HOST_NAME'
